sacca/web/forms/challenges.py
from wtforms import Form
from wtforms import fields
from wtforms import validators
from wtforms import widgets

from .fields import TagListField

from flask_wtf import FlaskForm, file


class TestCaseForm(FlaskForm):
    input_string = fields.TextAreaField('Input Text')
    input_file = fields.FileField('Input File')
    is_inputfile = fields.BooleanField('Is Input File', default=False)
    
    output_string = fields.TextAreaField('Output Text')
    output_file = fields.FileField('Output File')
    is_outputfile = fields.BooleanField('Is Output File', default=False)

    public = fields.BooleanField('Public', default=False)


class Solution(FlaskForm):
    code = file.FileField('File',
            validators=[file.FileRequired()]
            )

class ChallengeForm(FlaskForm):
    name = fields.StringField('Name',
            validators=[validators.InputRequired(),
                        validators.Length(min=3)])
    description = fields.StringField('Description',
            validators=[validators.InputRequired()])
    problem_statement = fields.StringField('Problem Statement',
            validators=[validators.InputRequired()],
            widget=widgets.TextArea())
    input_format = fields.StringField('Input Format',
            widget=widgets.TextArea())
    constraints = fields.StringField('Constraints',
            widget=widgets.TextArea())
    output_format = fields.StringField('Output Format',
            validators=[validators.InputRequired()],
            widget=widgets.TextArea())

    score = fields.IntegerField('Score',
            validators=[validators.InputRequired(),
                validators.NumberRange(min=0)],
            default=0)
    tags = TagListField('Tags',
            validators=[validators.InputRequired(),
                        validators.Length(min=3)])

sacca/web/views/assignments.py
from flask import (Blueprint,
                   render_template,
                   redirect,
                   request,
                   url_for)

from flask_login import current_user, login_required

from .. import acl
from .. import forms
from sacca import models

subviews = []

module = Blueprint('assignments',
                   __name__,
                   url_prefix='/assignments',
                   )


@module.route('/')
@login_required
def index():
    assignment_schedule = models.assignments.get_assignment_schedule(
            current_user._get_current_object())

    past_assignment_schedule = models.assignments.get_past_assignment_schedule(
            current_user._get_current_object())
    return render_template('/assignments/index.html',
                           assignment_schedule=assignment_schedule,
                           past_assignment_schedule=past_assignment_schedule)


@module.route('/<assignment_id>')
@login_required
def view(assignment_id):
    assignment = models.Assignment.objects.get(id=assignment_id)

    return render_template('/assignments/view.html',
                           assignment=assignment,
                           )


@module.route('/<assignment_id>/practice')
@login_required
def practice(assignment_id):
    class_ = None
    if request.args.get('class_id', None):
        class_ = models.Class.objects(
                id=request.args.get('class_id')).first()

    assignment = models.Assignment.objects.get(id=assignment_id)

    return render_template('/assignments/practice.html',
                           assignment=assignment,
                           class_=class_
                           )

sacca/web/views/challenges.py
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   url_for)
from flask_login import current_user, login_required

from .. import forms
from sacca import models

import datetime
import markdown
from pygments.formatters import HtmlFormatter

module = Blueprint('challenges',
                   __name__,
                   url_prefix='/challenges',
                   )


@module.route('/')
@login_required
def index():
    class_ = None
    if request.args.get('class_id', None):
        class_ = models.Class.objects(
                id=request.args.get('class_id')).first()

    challenges = []
    for assignment in class_.course.assignments:
        challenges.extend(assignment.challenges)
    return render_template('/challenges/index.html',
                           challenges=challenges,
                           class_=class_)


# @module.route('/create', methods=['GET', 'POST'])
# def create():
#     form = forms.challenges.ChallengeForm(request.form)
#     print(form.data)
#     if not form.validate_on_submit():
#         print(form.data)
#         return render_template('/administration/challenges/create.html',
#                                form=form)
#     data = form.data.copy()
#     data.pop('csrf_token')
#     challenge = models.Challenge(**data)
#     challenge.owner = current_user._get_current_object()
#     challenge.save()

#     return redirect(url_for('administration.challenges.view',
#                             challenge_id=challenge.id))

# @module.route('/<challenge_id>/add-testcase', methods=['GET', 'POST'])
# def add_testcase():
#     challenge = models.Challenge.objects.get(id=challenge_id)
#     form = forms.challenges.TestCaseForm(request.form)

#     if not form.validate_on_submit():
#         return redirect(url_for('administration.challenges.add_testcase',
#                                 challenge_id=challenge.id))

#     return redirect(url_for('administration.challenges.view',
#                             challenge_id=challenge.id))


@module.route('/<challenge_id>')
@login_required
def view(challenge_id):
    class_ = None
    if request.args.get('class_id', None):
        class_ = models.Class.objects(
                id=request.args.get('class_id')).first()
    challenge = models.Challenge.objects.get(id=challenge_id)

    user = current_user._get_current_object()
    solutions = models.Solution.objects(
            owner=user,
            enrolled_class=class_,
            challenge=challenge).order_by('-id')

    assignment = models.Assignment.objects(
            challenges=challenge,
            course=class_.course).first()
    assignment_time = class_.get_assignment_schedule(assignment)

    now = datetime.datetime.now()

    show_submission = (assignment_time.started_date <= now
                       and now < assignment_time.ended_date)

    formatter = HtmlFormatter(linenos=True)
    style = formatter.get_style_defs('.codehilite')

    challenge_status = models.ChallengeStatus.objects(
            user=user,
            enrolled_class=class_,
            challenge=challenge,
            assignment=assignment).first()
    if not challenge_status:
        challenge_status = models.ChallengeStatus(
                enrolled_class=class_,
                assignment=assignment,
                challenge=challenge,
                user=user
                )
        challenge_status.save()

    form = forms.challenges.Solution()

    return render_template(
            '/challenges/view.html',
            challenge=challenge,
            solutions=solutions,
            assignment=assignment,
            show_submission=show_submission,
            form=form,
            markdown=markdown.markdown,
            style=style,
            )


@module.route('/<challenge_id>/submit-solution', methods=['GET', 'POST'])
def submit_solution(challenge_id):
    class_ = models.Class.objects.get(id=request.args.get('class_id', None))
    challenge = models.Challenge.objects.get(id=challenge_id)

    assignment = models.Assignment.objects(
            challenges=challenge,
            course=class_.course).first()
    assignment_time = class_.get_assignment_schedule(assignment)

    now = datetime.datetime.now()

    form = forms.challenges.Solution()
    if not form.validate_on_submit():
        return render_template(
                '/challenges/view.html',
                challenge=challenge,
                assignment=assignment,
                show_submission=now < assignment_time.ended_date,
                form=form)

    if not now < assignment_time.ended_date:
        return redirect(url_for('challenges.view',
                                challenge_id=challenge.id,
                                class_id=class_.id))

    solution = models.Solution(owner=current_user._get_current_object(),
                               enrolled_class=class_,
                               assignment=assignment,
                               challenge=challenge,
                               language=class_.course.languages[0]
                               )
    solution.code.put(form.code.data,
                      filename=form.code.data.filename,
                      content_type=form.code.data.content_type)
    solution.save()
    return redirect(url_for('challenges.view',
                            challenge_id=challenge.id,
                            class_id=class_.id))

sacca/web/views/solutions.py
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   jsonify,
                   url_for)
from flask_login import current_user, login_required

from pygments.lexers import get_lexer_for_filename, get_lexer_by_name
from pygments import highlight
from pygments.formatters import HtmlFormatter

import difflib

from .. import acl
from .. import forms
from sacca import models


module = Blueprint('solutions',
                   __name__,
                   url_prefix='/solutions',
                   )


@module.route('/')
@login_required
def index():
    solutions = models.Solution.objects(
            owner=current_user._get_current_object()).order_by('-id')
    return render_template('/solutions/index.html',
                           solutions=solutions,
                           )


@module.route('/<solution_id>/')
@acl.allows.requires(acl.is_solution_owner)
def view(solution_id):
    solution = models.Solution.objects(
            id=solution_id,
            owner=current_user._get_current_object(),
            ).first()
    challenge = solution.challenge

    code = solution.code.read().decode(errors='ignore')

    lexer = get_lexer_for_filename(solution.code.filename)

    formatter = HtmlFormatter(linenos=True)
    formated_code = highlight(code, lexer, formatter)
    style = formatter.get_style_defs('.highlight')

    console_lexer = get_lexer_by_name("console")
    return render_template('/administration/solutions/view.html',
                           solution=solution,
                           challenge=challenge,
                           formated_code=formated_code,
                           console_lexer=console_lexer,
                           formatter=formatter,
                           highlight=highlight,
                           difflib=difflib,
                           style=style)


@module.route('/<solution_id>/status')
@acl.allows.requires(acl.is_solution_owner
                     or acl.is_lecturer
                     or acl.is_teaching_assistant)
def status_api(solution_id):
    solution = models.Solution.objects(
            id=solution_id,
            owner=current_user._get_current_object(),
            ).first()
    data = dict(id=solution_id,
                status=solution.status,
                score=solution.score,
                passed=solution.passed)
    return jsonify(data)

sacca/web/templates/challenges/index.html
{% extends '/base/default-dashboard.html' %}

{% block dashboard_title %}Challenges{% endblock %}

{% block breadcrumbs %}
<a href="{{ url_for('challenges.index', **request.args.to_dict()) }}" class="section">Challenges</a>
{% endblock %}

{% block content %}

<div class="ui container">
      <table class="ui celled table">
        <thead>
          <tr>
              <th>Name</th>
              <th>Score</th>
              <th>Tags</th>
              <th>Your Scores</th>
          </tr>
        </thead>
        <body>
  {% for challenge in challenges %}
          <tr>
            <td>
              <a href="{{ url_for('challenges.view', challenge_id=challenge.id, **request.args.to_dict()) }}">{{ challenge.name }}</a>
            </td>
            <td>
                {{challenge.score}}
            </td>
            <td>
                {{ challenge.tags | join(', ') }}
            </td>
            <td class="right aligned">
              {{ '{:.02f}'.format(challenge.get_solution_score(class_, current_user)) }}
            </td>
          </tr>
  {% endfor %}
        </body>
      </table>
</div>

{% endblock %}

sacca/web/templates/challenges/view.html
{% extends '/challenges/index.html' %}
{% import '/base/html-renderer.html' as renderer %}
{% import '/base/solution-style.html' as solution_style %}

{% block additional_head %}
{{ super() }}

<style type="text/css">
  {{ style }}
</style>
{% endblock %}

{% block additional_js %}
  {{ super() }}

<script type="text/x-mathjax-config">
MathJax.Hub.Config({
  config: ["MMLorHTML.js"],
  jax: ["input/TeX", "output/HTML-CSS", "output/NativeMML"],
  extensions: ["MathMenu.js", "MathZoom.js"]
});
</script>
<script type="text/javascript" src="{{ url_for('static', filename='node_modules/mathjax/MathJax.js') }}"></script>

<script type="text/javascript">
  $(".attach-file-code").click(function() {
    $(this).parent().find("#code").click();
  });

  $('#code')
    .on('change', function(e) {
      var name = e.target.files[0].name;
      $('.attach-file-code', $(e.target).parent()).val(name);
    });
</script>


<script type="text/javascript" src="{{ url_for('static', filename='node_modules/brython/brython.js') | add_date_url}}"></script>
<script type="text/javascript" src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') | add_date_url}}"></script>
  <script type="text/javascript">
    brython(1);
  </script>

{% endblock %}


{% block dashboard_title %}
Challenge: {{ challenge.name }}
{% endblock %}

{% block breadcrumbs %}
  {{ super() }}  
  <i class="right chevron icon divider"></i>
  <a href="{{ url_for('challenges.view', challenge_id=challenge.id, **request.args.to_dict()) }}" class="active section">{{ challenge.name }}</a>
{% endblock %}

{% block content %}
<div class="ui container">
  <div class="ui info message">
    <h2 class="header">
      Assignment: <a href="{{ url_for('assignments.practice', assignment_id=assignment.id,  **request.args.to_dict()) }}">{{ assignment.name }}</a>
    </h2>
  </div>
</div>

<div class="ui container" style="margin-top: 1em;">
  <div class="ui segment big" style="line-height: normal;">
		<h3>{{ challenge.name }}</h3>
		{#
		<h4>Description</h4>
		<div>
			{{ challenge.description }}
		</div>
		#}
		<h4>Problem Statement</h4>
		<div>
			{{ markdown(challenge.problem_statement, extensions=['fenced_code', 'codehilite', 'mdx_math', 'tables']) | safe }}
		</div>

		<h4>Input Format</h4>
		<div>
			{{ challenge.input_format if challenge.input_format and challenge.input_format | count > 0 else '-' }}
		</div>

		<h4>Constrains</h4>
		<div>
			{{ challenge.constrains if challenge.constrains and challenge.constrains | count > 0 else '-'}}
		</div>

		<h4>Output Format</h4>
		<div>
			{{ markdown(challenge.output_format, extensions=['fenced_code', 'codehilite', 'mdx_math', 'tables']) | safe }}
		</div>

		<h4>Score</h4>
		<div>
      <span class="ui red text"><b>{{ challenge.score }}</b></span>
		</div>

		<h4>Tags</h4>
		<div>
      {{ challenge.tags | join(', ') }}
    </div>

    {%- if challenge.test_cases | count > 0 %}
		<h4>Public Test Case</h4>
    <table class="ui celled blue table">
      <thead>
        <tr>
            <th>Input</th>
            <th>System Output</th>
        </tr>
      </thead>

      <tbody>
        {%- for t in challenge.test_cases if t.public %}
        <tr>
          <td><pre>{{ t.input_string }}</pre></td>
          <td>
            <pre>{{ t.output_string }}</pre>
          </td>
        </tr>
        {% endfor -%}
      </tbody>
    </table>
    {% endif -%}
  </div>
</div>

{% if request.args.get('class_id', None) %}
{% if show_submission %}
<div class="ui container" style="margin-top: 1em;">
	<div class="ui segment">
		<form class="ui form" action="{{ url_for('challenges.submit_solution', challenge_id=challenge.id, class_id=request.args.get('class_id')) }}" enctype="multipart/form-data" method="POST">
			{{ form.csrf_token }}
			{{ renderer.render_fileinput(form.code) }}
			<button name="submit" type="submit" class="ui primary button">Submit</button>
		</form>
  </div>
</div>
{% endif %}

<div class="ui container" style="margin-top: 1em;">
  {% if solutions %}
<script type="text/python">
  from browser import document, html, ajax, timer
  import json

  sol_status = {}
  _timer = None

  url = "{{ url_for('solutions.status_api', solution_id='solution_id') }}"

  def set_get_status_timeout():
    global _timer
    if _timer:
      timer.clear_timeout(_timer)

    _timer = timer.set_timeout(get_status_from_server, 5000)

  def on_complete(req):
    global sol_status

    obj = json.loads(req.text)
    print('got status', obj)

    old_status = sol_status[obj['id']]
    if old_status == obj['status']:
      set_get_status_timeout()
      return
  
    tr = document['solution-'+obj['id']]
    for td in tr.children:
      if td.headers == 'status':
        td.text = obj['status']
      elif td.headers == 'passed':
        td.text = obj['passed']
      elif td.headers == 'score':
        td.text = obj['score']

    if obj['status'] == 'complete':
      if obj['passed'] == True:
        tr.className = 'positive'
      else:
        tr.className = 'negative'

      a = document[f'solution-{obj["id"]}-view']
      a.className = a.className.replace('disabled', '').strip()

      sol_status.pop(obj['id'])
    else:
      set_get_status_timeout()



  def check_solution_status():
    sol_status = {}
    trs = document['solution-status'].children
    for tr in trs:
      for td in tr.children:
        if td.headers == 'status' and td.text.strip() != 'complete':
          solution_id = tr.id.split('-')[-1]
          sol_status[solution_id] = td.text.strip()
          break
    return sol_status

  def get_status_from_server():
    global sol_status
    for sol_id in sol_status:
      request_url = url.replace('solution_id', sol_id)
      ajax.get(request_url, oncomplete=on_complete)

  sol_status = check_solution_status()
  if len(sol_status) > 0:
    get_status_from_server()

</script>
		  <table class="ui celled table">
        <thead>
          <tr>
            <th>Filename</th>
            <th>Submited Date</th>
            <th>Status</th>
            <th>Pass</th>
            <th>Score</th>
            <th>Operations</th>
          </tr>
        </thead>

        <tbody id="solution-status">
          {% for solution in solutions %}
          <tr id="solution-{{ solution.id }}" class="{{ solution_style.get_solution_class(solution) }}">
            <td headers="filename">{{ solution.code.filename }}</td>
            <td headers="submitted_date">{{ solution.submitted_date }}</td>
            <td headers="status">{{ solution.status }}</td>
            <td headers="passed">{{ solution.passed }}</td>
            <td headers="score">{{ '{:.2f}'.format(solution.score) }}</td>
            <td headers="operation">
              {% if solution.status == 'complete' %}
                <a id="solution-{{ solution.id }}-view" class="ui circular primary icon button" target="blank" href="{{ url_for('solutions.view', solution_id=solution.id, class_id=request.args.get('class_id')) }}"><i class="eye icon"></i></a>
              {% else %}
                <a id="solution-{{ solution.id }}-view" class="ui circular primary icon button disabled" target="blank" href="{{ url_for('solutions.view', solution_id=solution.id, class_id=request.args.get('class_id')) }}"><i class="eye icon"></i></a>
              {% endif %}
            </td>
					</tr>
          {% endfor %}
        </tbody>
		  </table>
	  {% endif %}
</div>
{% endif %}

{% endblock %}