sacca/web/views/solutions.py
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   jsonify,
                   url_for)
from flask_login import current_user, login_required

from pygments.lexers import get_lexer_for_filename, get_lexer_by_name
from pygments import highlight
from pygments.formatters import HtmlFormatter

import difflib

from .. import acl
from .. import forms
from sacca import models


module = Blueprint('solutions',
                   __name__,
                   url_prefix='/solutions',
                   )


@module.route('/')
@login_required
def index():
    solutions = models.Solution.objects(
            owner=current_user._get_current_object()).order_by('-id')
    return render_template('/solutions/index.html',
                           solutions=solutions,
                           )


@module.route('/<solution_id>/')
@acl.allows.requires(acl.is_solution_owner)
def view(solution_id):
    solution = models.Solution.objects(
            id=solution_id,
            owner=current_user._get_current_object(),
            ).first()
    challenge = solution.challenge

    code = solution.code.read().decode(errors='ignore')

    lexer = get_lexer_for_filename(solution.code.filename)

    formatter = HtmlFormatter(linenos=True)
    formated_code = highlight(code, lexer, formatter)
    style = formatter.get_style_defs('.highlight')

    console_lexer = get_lexer_by_name("console")
    return render_template('/administration/solutions/view.html',
                           solution=solution,
                           challenge=challenge,
                           formated_code=formated_code,
                           console_lexer=console_lexer,
                           formatter=formatter,
                           highlight=highlight,
                           difflib=difflib,
                           style=style)


@module.route('/<solution_id>/status')
@acl.allows.requires(acl.is_solution_owner
                     or acl.is_lecturer
                     or acl.is_teaching_assistant)
def status_api(solution_id):
    solution = models.Solution.objects(
            id=solution_id,
            owner=current_user._get_current_object(),
            ).first()
    data = dict(id=solution_id,
                status=solution.status,
                score=solution.score,
                passed=solution.passed)
    return jsonify(data)

sacca/web/templates/solutions/index.html
{% extends '/base/default-dashboard.html' %}
{% import '/base/solution-style.html' as solution_style %}

{% block breadcrumbs %}
<a href="{{ url_for('solutions.index') }}" class="section">Solutions</a>
{% endblock %}

{% block dashboard_title %}
Submitted Soulutions
{% endblock %}

{% block content %}
<div class="ui container">
  <table class="ui celled table">
    <thead>
      <tr>
        <th>Challenge Name</th>
        <th>Class Name</th>
        <th>Submitted Date</th>
        <th>Check Status</th>
        <th>Pass Test</th>
        <th>Score</th>
        <th>Operation</th>
      </tr>
    </thead>
    <tbody>
{% for solution in solutions %}
      <tr class="{{ solution_style.get_solution_class(solution) }}">
        <td>
          <a href="{{ url_for('challenges.view', challenge_id=solution.challenge.id, class_id=solution.enrolled_class.id) }}">{{ solution.challenge.name }}</a>
        </td>
        <td>
          <a href="{{ url_for('classes.view', class_id=solution.enrolled_class.id) }}">{{ solution.enrolled_class.name }}</a>
        </td>
        <td>
          {{ solution.submitted_date.ctime() }}
        </td>
        <td>
          {{ solution.status }}
        </td>
        <td>
          {{ solution.passed }}
        </td>
        <td>
          {{ '{:.2f}'.format(solution.score) }}
        </td>
        <td>
            {% if solution.status == 'complete' %}
              <a href="{{ url_for('solutions.view', solution_id=solution.id, class_id=request.args.get('class_id')) }}" class="ui circular primary icon button"><i class="eye icon"></i></a>
            {% else %}
              <i class="eye icon"></i>
            {% endif %}
        </td>
      </tr>
{% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}