sacca/web/views/classes.py
from flask import (Blueprint,
                   render_template,
                   url_for,
                   redirect
                   )
from flask_login import current_user, login_required

from .. import forms
from sacca import models

module = Blueprint('classes',
                   __name__,
                   url_prefix='/classes',
                   )


@module.route('/')
@login_required
def index():
    enrollments = models.Enrollment.objects(
            user=current_user._get_current_object())
    return render_template('/classes/index.html',
                           enrollments=enrollments)

@module.route('/<class_id>')
@login_required
def view(class_id):
    class_ = models.Class.objects.get(id=class_id)
    enrollment = models.Enrollment.objects(
            user=current_user._get_current_object(),
            enrolled_class=class_).first()
    return render_template('/classes/view.html',
                           enrollment=enrollment,
                           class_=class_)

@module.route('/<class_id>/enroll')
@login_required
def enroll(class_id):
    class_ = models.Class.objects.get(id=class_id)
    enrollment = models.Enrollment.objects(
            user=current_user._get_current_object(),
            enrolled_class=class_).first()
    if not enrollment:
        enrollment = models.Enrollment(
                user=current_user._get_current_object(),
                enrolled_class=class_)
        enrollment.save()

    return redirect(url_for('classes.view', class_id=class_.id))

sacca/web/views/scoreboards.py
from flask import (Blueprint,
                   render_template,
                   request,
                   redirect,
                   url_for,
                   jsonify)
from flask_login import current_user, login_required

from .. import forms
from sacca import models

module = Blueprint('scoreboards', __name__, url_prefix='/scoreboards')


@module.route('/classes/<class_id>/assignments/<assignment_id>')
def show_assignment_scores(class_id, assignment_id):
    class_ = models.Class.objects.get(id=class_id)
    assignment = models.Assignment.objects.get(id=assignment_id)

    return render_template('scoreboards/show_assignment_scores.html',
                           class_=class_,
                           assignment=assignment)

@module.route('/classes/<class_id>/assignments/<assignment_id>/scores')
def list_assignment_scores(class_id, assignment_id):
    class_ = models.Class.objects.get(id=class_id)
    assignment = models.Assignment.objects.get(id=assignment_id)
    if not assignment:
        return

    challenge_count = len(assignment.challenges)

    data = dict()
    for e in class_.get_enrollments():
        data[str(e.user.id)] = dict(
                name=e.user.first_name,
                score=assignment.get_score(class_, e.user),
                max_score=assignment.score,
                complete=assignment.count_done_challenges(class_, e.user),
                challenges=challenge_count,
                )

    return jsonify(data)

sacca/web/templates/scoreboards/index.html
{% extends '/base/default-dashboard.html' %}

{% block dashboard_title %}
  Scoreboard
{% endblock %}
{% block breadcrumbs %}
<a href="{{ url_for('classes.index', **request.args.to_dict()) }}" class="section">Class</a>
{% endblock %}

{% block content %}
  <div class="ui container">
  </div>
{% endblock %}

sacca/web/templates/scoreboards/show_assignment_scores.html
{% extends '/scoreboards/index.html' %}

{% block additional_js %}
  <script src="//cdnjs.cloudflare.com/ajax/libs/fabric.js/3.6.3/fabric.js"></script>

  <script type="text/javascript" src="{{ url_for('static', filename='node_modules/brython/brython.js') }}"></script>
  <script type="text/javascript" src="{{ url_for('static', filename='node_modules/brython/brython_stdlib.js') }}"></script>
  <script src="{{ url_for('static', filename='brython/scoreboards.brython.js') }}"></script>

  <script type="text/javascript">
    brython(1);
  </script>
{% endblock %}

{% block dashboard_title %}Scoreboard: {{ class_.name }}{% endblock %}

{% block breadcrumbs %}
{{ super() }}
<i class="right angle icon divider"></i>
<div class="active section">{{ class_.name }}</div>
{% endblock %}


{% block content %}
  <div>
    <canvas id="scoreboard" style="width: 100%!important; height: 80vh;"></canvas>
  </div>
  <script type="text/python">
    from scoreboards import display
    from browser import document

    score_board = display.ScoreBoard(
        'scoreboard',
        width=document['scoreboard'].parent.width,
        height=document['scoreboard'].parent.height,
        data_url="{{ url_for('scoreboards.list_assignment_scores', class_id=class_.id, assignment_id=assignment.id) }}"
        )
    score_board.run()
  </script>
{% endblock %}