sacca/web/views/assignments.py
from flask import (Blueprint,
                   render_template,
                   redirect,
                   request,
                   url_for)

from flask_login import current_user, login_required

from .. import acl
from .. import forms
from sacca import models

subviews = []

module = Blueprint('assignments',
                   __name__,
                   url_prefix='/assignments',
                   )


@module.route('/')
@login_required
def index():
    assignment_schedule = models.assignments.get_assignment_schedule(
            current_user._get_current_object())

    past_assignment_schedule = models.assignments.get_past_assignment_schedule(
            current_user._get_current_object())
    return render_template('/assignments/index.html',
                           assignment_schedule=assignment_schedule,
                           past_assignment_schedule=past_assignment_schedule)


@module.route('/<assignment_id>')
@login_required
def view(assignment_id):
    assignment = models.Assignment.objects.get(id=assignment_id)

    return render_template('/assignments/view.html',
                           assignment=assignment,
                           )


@module.route('/<assignment_id>/practice')
@login_required
def practice(assignment_id):
    class_ = None
    if request.args.get('class_id', None):
        class_ = models.Class.objects(
                id=request.args.get('class_id')).first()

    assignment = models.Assignment.objects.get(id=assignment_id)

    return render_template('/assignments/practice.html',
                           assignment=assignment,
                           class_=class_
                           )

sacca/web/views/classes.py
from flask import (Blueprint,
                   render_template,
                   url_for,
                   redirect
                   )
from flask_login import current_user, login_required

from .. import forms
from sacca import models

module = Blueprint('classes',
                   __name__,
                   url_prefix='/classes',
                   )


@module.route('/')
@login_required
def index():
    enrollments = models.Enrollment.objects(
            user=current_user._get_current_object())
    return render_template('/classes/index.html',
                           enrollments=enrollments)

@module.route('/<class_id>')
@login_required
def view(class_id):
    class_ = models.Class.objects.get(id=class_id)
    enrollment = models.Enrollment.objects(
            user=current_user._get_current_object(),
            enrolled_class=class_).first()
    return render_template('/classes/view.html',
                           enrollment=enrollment,
                           class_=class_)

@module.route('/<class_id>/enroll')
@login_required
def enroll(class_id):
    class_ = models.Class.objects.get(id=class_id)
    enrollment = models.Enrollment.objects(
            user=current_user._get_current_object(),
            enrolled_class=class_).first()
    if not enrollment:
        enrollment = models.Enrollment(
                user=current_user._get_current_object(),
                enrolled_class=class_)
        enrollment.save()

    return redirect(url_for('classes.view', class_id=class_.id))

sacca/web/views/courses.py
from flask import (Blueprint,
                   render_template,
                   url_for,
                   redirect
                   )
from flask_login import current_user, login_required

from .. import acl
from .. import forms
from sacca import models

import mongoengine as me

import datetime

module = Blueprint('courses',
                   __name__,
                   url_prefix='/courses',
                   )



@module.route('/')
@login_required
def index():
    classes = models.Class.objects(
            me.Q(limited_enrollment__grantees=current_user.username) |
            me.Q(limited_enrollment__grantees=current_user.email) )

    courses = [class_.course for class_ in classes]
    
    return render_template('/courses/index.html',
                           courses=courses)

@module.route('/<course_id>')
@login_required
def view(course_id):
    now = datetime.datetime.now()
    course = models.Course.objects.get(id=course_id)
    classes = models.Class.objects(
            me.Q(course=course) &
            (me.Q(limited_enrollment__grantees=current_user.username) |
             me.Q(limited_enrollment__grantees=current_user.email)) &
            (me.Q(started_date__lte=now) &
             me.Q(ended_date__gte=now))
            )
    enrolled_classes = []
    for class_ in classes:
        enrollment = models.Enrollment.objects(
                user=current_user._get_current_object(),
                enrolled_class=class_).first()
        if enrollment:
            enrolled_classes.append(enrollment.enrolled_class)
    return render_template('/courses/view.html',
                           course=course,
                           enrolled_classes=enrolled_classes,
                           classes=classes)

sacca/web/templates/classes/index.html
{% extends '/base/default-dashboard.html' %}

{% block breadcrumbs %}
<a href="{{ url_for('classes.index') }}" class="section">Classes</a>
{% endblock %}

{% block dashboard_title %}Enrolled Classes{% endblock %}

{% block content %}
  <div class="ui container">
    {% if enrollments %}
    <table class="ui celled table">
      <thead>
        <tr>
          <th>Name</th>
          <th>Description</th>
        </tr>
      </thead>
      <body>
  {% for enrollment in enrollments %}
        <tr>
          <td>
            <a href="{{ url_for('classes.view', class_id=enrollment.enrolled_class.id) }}">{{ enrollment.enrolled_class.name }}</a>
          </td>
          <td>
            {{ enrollment.enrolled_class.description }}
          </td>
        </tr>
  {% endfor %}
      </body>
    </table>
    {% endif %}
</div>

{% endblock %}

sacca/web/templates/classes/view.html
{% extends '/classes/index.html' %}

{% block dashboard_title %}
  Class: {{ class_.name }}
{% endblock %}

{% block breadcrumbs %}
  {{ super() }}
  <i class="right angle icon divider"></i>
  <div class="active section">{{ class_.name }}</div>
{% endblock %}

{% block content %}
<div class="ui container">
  <div class="ui segment">
		<h3>{{ class_.name }}</h3>
		<div>
			{% if enrollment %}
				You enroll this class
			{% else %}
			<a class="btn-floating btn-small waves-effect waves-light red" href="{{ url_for('classes.enroll', class_id=class_.id) }}"><i class="material-icons">add</i></a>

			{% endif %}
		</div>

		<div>
			<b>Description:</b> {{ class_.description }}
		</div>
		<div>
			<b>Code:</b> {{ class_.code }}
		</div>
		<div>
			<b>Course:</b> <a href="{{ url_for('courses.view', course_id=class_.course.id) }}">{{ class_.course.name }}</a>
		</div>
		<div>
			<b>Limited Class:</b> {{ class_.limited }}
		</div>
		<div>
			<b>Started Date:</b> {{ class_.started_date }}
		</div>
		<div>
			<b>Ended Date:</b> {{ class_.ended_date }}
		</div>

		<div>
			<b>Tag:</b> {{ class_.tags | join(', ') }}
		</div>
  </div>

  <div style="margin-top: 1em;">
		<h3>Assignments</h3>
		<table class="ui celled blue table">
			<thead>
				<tr>
					<th>Name</th>
					<th>Challenges</th>
					<th>Start</th>
					<th>End</th>
					<th>Operation</th>
				</tr>
			</thead>

			<tbody>
				{% for ass_time in class_.assignment_schedule %}
				<tr>
					<td>
						<a href="{{ url_for('assignments.practice', assignment_id=ass_time.assignment.id, class_id=class_.id) }}">
							{{ ass_time.assignment.name }}
						</a>
					</td>
					<td>{{ ass_time.assignment.challenges | count }}</td>
					<td>{{ ass_time.started_date }}</td>
					<td>{{ ass_time.ended_date }}</td>
          <td>
            <a class="ui circular primary icon button" href="{{ url_for('assignments.practice', assignment_id=ass_time.assignment.id, class_id=class_.id) }}">
              <i class="eye icon"></i>
            </a>
          </td>
				</tr>
			{% endfor %}
			</tbody>
		</table>
            	
  </div>
</div>
{% endblock %}